#! /bin/bash

echo "STARTING UPDATES"
sudo apt-get update > ktmp.log
sudo apt-get upgrade > ktmp.log


cd
echo "STARTING INSTALL FOR NECCECERRY TOOLS"
sudo apt-get install git wget gdebi openssh-server vim > ktmp.log

echo "STARTING INSTALL FOR OTHER APPLICATIONS"
sudo apt-get install cmatrix gcc g++ clang perl ruby python python-pip python3 python3-pip htop firefox konsole terminator xterm nano gedit leafpad gnome-terminal > ktmp.log
sudo pip3 install slowloris > ktmp.log

echo "STARTING INSTALL FOR VIM SETTINGS"
cd Downloads
git clone https://github.com/SladetBask-Kasper/VimSettings.git > ktmp.log
cd VimSettings
mv vim.vim ~/.vim
mv k.vimrc ~/.vimrc
cd

rm ktmp.log
