#! /bin/bash
cd

echo "STARTING UPDATES"
sudo apt-get update
sudo apt-get upgrade


cd
echo "STARTING INSTALL FOR NECCECERRY TOOLS"
sudo apt-get install git wget gdebi openssh-server vim

echo "STARTING INSTALL FOR OTHER APPLICATIONS"
sudo apt-get install cmatrix gcc g++ gfortran clang perl ruby python python-pip python3 python3-pip htop firefox konsole terminator xterm nano gedit leafpad gnome-terminal steam
sudo pip3 install slowloris

echo ""
echo "SETTING UP PROGRAMMING FOLDERS..."
cd ~
mkdir programming
cd programming
mkdir cpp
mkdir c
mkdir perl
mkdir python
mkdir lua
mkdir ruby
mkdir frotran
mkdir random

## The Following does not work propoly.

#echo "STARTING INSTALL FOR VIM SETTINGS"
#cd Downloads
#echo "gettin vim settings"
#git clone https://github.com/SladetBask-Kasper/VimSettings.git > ktmp.log
#cd VimSettings
#mv vim.vim ~/.vim
#mv k.vimrc ~/.vimrc
cd

